apiVersion: apps/v1
kind: Deployment
metadata:
  name: hrm-deployment
  labels:
    bilal: bilal
spec:
  replicas: 1
  selector:
    matchLabels:
      bilal: bilal
  template:
    metadata:
      labels:
        bilal: bilal
    spec:
      containers:
      - name: hrm-container
        image: bitnami/orangehrm-archived
        ports:
        - containerPort: 8080
        env:
        - name: ORANGEHRM_DATABASE_HOST
          value: maria-svc
        - name: ORANGEHRM_DATABASE_USER
          value: bn_orangehrm
        - name: ORANGEHRM_DATABASE_PASSWORD
          value: bitnami
        - name: ORANGEHRM_ROOT_PASSWORD
          value: kanzalpass