apiVersion: v1
kind: Pod
metadata:
  name: maria-pod
  labels:
    noman: noman
spec:
  containers:
  - name: maria-container
    image: mariadb:10.6
    ports:
    - containerPort: 3306
    env:
    - name: MARIADB_DATABASE
      value: mariadb
    - name: MARIADB_USER
      value: kanzal
    - name: MARIADB_PASSWORD
      value: kanzalpass
    - name: MYSQL_ROOT_PASSWORD
      value: root