resources:
- wp-pvc.yaml
- configmap.yaml
- wp-secret.yaml
- db-secret.yaml
- mysql-sts.yaml
- wp-depl.yaml
- mysql-h-svc.yaml
- wp-svc.yaml


# Storage Class
#    allowVolumeExpansion
#    mountOptions
#    parameters
#    provisioner
#    reclaimPolicy
#    volumeBindingMode  ----1) Immediate 2) WaitForFirstConsumer

# Persistent Volume
#    capacity
#    accessModes
#    persistentVolumeReclaimPolicy
#    storageClassName
#    mountOptions
#    volumeMode

# Persistent Volume Claim
#    accessModes
#    resources
#    storageClassName
#    volumeMode
#    volumeName