apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: mysql
  namespace: wp  
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: db-vol
        persistentVolumeClaim:
          claimName: db-pvc
      containers:
      - name: mysql-cntr
        image: mysql
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: db-vol
          mountPath: /var/lib/mysql
        envFrom:
        - secretRef:
            name: db-secret
