apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: wp
spec:
  serviceName: mysql-headless
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
              name: mysql
          envFrom:
          - secretRef:
              name: db-secret
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: nfs-sc
        resources:
          requests:
            storage: 3Gi

                   


