apiVersion: v1
kind: Pod
metadata:
  namespace: wp
  name: mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: mysql-cntr
    image: mysql
    ports:
    - containerPort: 3306
    envFrom:
    - secretRef:
        name: db-secret
