apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wordpress
  namespace: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wp-cotr
        image: wordpress
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: wp-configmap
        - secretRef:
            name: wp-secret
