apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-deployment
  labels:
    app: wordpress
  namespace: wp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
      - name: wp-vol
        persistentVolumeClaim:
          claimName: wp-pvc
      containers:
      - name: wp-cotr
        image: wordpress
        volumeMounts:
        - name: wp-vol
          mountPath: /var/www/html
        ports:
        - containerPort: 80
        envFrom:
        - configMapRef:
            name: wp-configmap
        - secretRef:
            name: wp-secret
