apiVersion: v1
kind: Service
metadata:
  name: wp-svc
#  namespace: wp
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000